In [40]:
train_data_matrix = create_data_matrix(train_data, n_users, n_items)
test_data_matrix = create_data_matrix(test_data, n_users, n_items)
print(train_data_matrix)
print(test_data_matrix)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [37]:
import numpy as np
def create_data_matrix(data, n_users, n_items):
    # Use the max IDs from the data to ensure proper matrix size
    max_user_id = data["u"].max()
    max_item_id = data["i"].max()
    data_matrix = np.zeros((max_user_id + 1, max_item_id + 1))
    data_matrix[data["u"].values, data["i"].values] = 1
    return data_matrix


In [31]:
train_data = interactions[interactions["pct_rank"] < 0.8]
test_data = interactions[interactions["pct_rank"] >= 0.8]
print("Training set size:", train_data.shape[0])
print("Testing set size:", test_data.shape[0])

Training set size: 65419
Testing set size: 21628


In [26]:
interactions["pct_rank"] = interactions.groupby("u")["t"].rank(pct=True, method='dense')
interactions.reset_index(inplace=True, drop=True)
interactions.head(10)

u  i             t  pct_rank
0  0  0  1.680191e+09      0.04
1  0  1  1.680783e+09      0.08
2  0  2  1.680801e+09      0.12
3  0  3  1.683715e+09      0.16
4  0  3  1.683715e+09      0.20
5  0  4  1.686569e+09      0.24
6  0  5  1.687014e+09      0.28
7  0  6  1.687014e+09      0.32
8  0  7  1.687014e+09      0.36
9  0  8  1.687260e+09      0.40

In [30]:
interactions = interactions.sort_values(["u", "t"])
interactions.head(10)

u  i             t  pct_rank
0  0  0  1.680191e+09      0.04
1  0  1  1.680783e+09      0.08
2  0  2  1.680801e+09      0.12
3  0  3  1.683715e+09      0.16
4  0  3  1.683715e+09      0.20
5  0  4  1.686569e+09      0.24
6  0  5  1.687014e+09      0.28
7  0  6  1.687014e+09      0.32
8  0  7  1.687014e+09      0.36
9  0  8  1.687260e+09      0.40

In [17]:
n_users = interactions.u.nunique()
n_items = interactions.i.nunique()
print(f'Number of users = {n_users}, \n Number of books = {n_items} \n Number of interactions = {len(interactions)}')

Number of users = 7838, 
 Number of books = 15109 
 Number of interactions = 87047


In [18]:
correct.head()

user_id                                     recommendation
0        0  3758 11248 9088 9895 5101 6074 9295 14050 1096...
1        1  3263 726 1589 14911 6432 10897 6484 7961 8249 ...
2        2  13508 9848 12244 2742 11120 2893 2461 5439 116...
3        3  2821 10734 6357 5934 2085 12608 12539 10551 10...
4        4  12425 219 11602 1487 14178 489 13888 2110 4413...

In [35]:
interactions.head()

u      i             t
0  4456   8581  1.687541e+09
1   142   1964  1.679585e+09
2   362   3705  1.706872e+09
3  1809  11317  1.673533e+09
4  4384   1323  1.681402e+09

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

# Load dataset
interactions = pd.read_csv('/Users/kaita/Documents/Librarian_Recommender_DSML/data/interactions_train.csv')
items = pd.read_csv('/Users/kaita/Documents/Librarian_Recommender_DSML/data/items.csv')
correct = pd.read_csv('/Users/kaita/Documents/Librarian_Recommender_DSML/data/sample_submission.csv')

items.head()

Title  \
0  Classification décimale universelle : édition ...   
1  Les interactions dans l'enseignement des langu...   
2  Histoire de vie et recherche biographique : pe...   
3  Ce livre devrait me permettre de résoudre le c...   
4                    Les années glorieuses : roman /   

                     Author  \
0                       NaN   
1  Cicurel, Francine, 1947-   
2                       NaN   
3     Mazas, Sylvain, 1980-   
4   Lemaitre, Pierre, 1951-   

                                          ISBN Valid     Publisher  \
0                          9782871303336; 2871303339   Ed du CEFAL   
1                          9782278058327; 2278058320        Didier   
2                          2343190194; 9782343190198   L'Harmattan   
3  9782365350020; 236535002X; 9782365350488; 2365...       Vraoum!   
4  9782702180815; 2702180817; 9782702183618; 2702...  Calmann-Lévy   

                                            Subjects  i  
0  Classification décimale universelle; Indexatio...  0  
1  didactique--langue étrangère - enseignement; d...  1  
2  Histoires de vie en sociologie; Sciences socia...  2  
3  Moyen-Orient; Bandes dessinées autobiographiqu...  3  
4  France--1945-1975; Roman historique; Roman fra...  4